name: value
version: 0.0.1
description: >
  Value types macro.
repository: https://github.com/google/built_value.dart/tree/master/built_value

environment:
  sdk: '>=3.3.0-edge <4.0.0'

dev_dependencies:
  args: ^2.3.0
  checks: ^0.2.0
  test: ^1.24.0
  dart_style: ^2.2.1
  _fe_analyzer_shared: any
  frontend_server: any
  build_runner: ^2.4.7

# Override to the latest version of the in progress api.
dependency_overrides:
  _fe_analyzer_shared:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/_fe_analyzer_shared
  _js_interop_checks:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/_js_interop_checks
  analyzer:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/analyzer
  build_integration:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/build_integration
  compiler:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/compiler
  dart2wasm:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/dart2wasm
  dart2js_info:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/dart2js_info
  dev_compiler:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/dev_compiler
  front_end:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/front_end
  frontend_server:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/frontend_server
  js_ast:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/js_ast
  js_runtime:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/js_runtime
  js_shared:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/js_shared
  kernel:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/kernel
  meta:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/meta
  mmap:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/mmap
  vm:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/vm
  wasm_builder:
    path: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/pkg/wasm_builder
