targets:
  $default:
    builders:
      to_string_generator|to_string_generator:
        enabled: true

builders:
  to_string_generator:
    target: ":to_string_generator"
    import: "package:to_string_generator/builder.dart"
    builder_factories: ["builder"]
    build_extensions: {".dart": [".to_string.dart"]}
    auto_apply: dependents
    build_to: source
