name: built_value_test
version: 4.6.1
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library provides test support.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_value: ^4.6.1
  built_collection: '>=2.0.0 <4.0.0'
  collection: ^1.0.0
  quiver: '>=0.21.0 <0.28.0'
  test: any

dev_dependencies:
  build: ^0.11.1
  build_runner: ^0.6.0
  built_value_generator: ^4.6.1
  source_gen: ^0.7.0
