name: built_value_macro
version: 8.9.2
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the runtime dependency.
repository: https://github.com/google/built_value.dart/tree/master/built_value
topics:
 - built-value

environment:
  sdk: '>=3.5.0-0 <4.0.0'

dependencies:
  built_collection: ^5.0.0
  collection: ^1.15.0
  macros: ^0.1.0-main
  fixnum: ^1.0.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.4.0
  test: ^1.16.0

dependency_overrides:
  analyzer:
    path: ../../dart-sdk/sdk/pkg/analyzer
  built_value_generator:
    path: ../built_value_generator
  macros:
    path: ../../dart-sdk/sdk/pkg/macros
  _fe_analyzer_shared:
    path: ../../dart-sdk/sdk/pkg/_fe_analyzer_shared
