targets:
  $default:
    builders:
      equals_generator|equals_generator:
        enabled: true

builders:
  equals_generator:
    target: ":equals_generator"
    import: "package:equals_generator/builder.dart"
    builder_factories: ["builder"]
    build_extensions: {".dart": [".equals.dart"]}
    auto_apply: dependents
    build_to: source
