name: benchmark_large_library_cycle
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.7.0

dev_dependencies:
  build: '>=1.0.0 <3.0.0'
  build_runner: '>=1.0.0 <3.0.0'
  built_value_generator: ^8.9.2
  fixnum: ^1.0.0
  pedantic: ^1.4.0
  quiver: '>=0.21.0 <4.0.0'
  test: ^1.16.0
