name: built_value_analyzer_plugin
version: 5.2.0
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the Dart analyzer plugin.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  analyzer: '>=0.31.0 <0.32.0'
  analyzer_plugin: ^0.0.1-alpha.0
  built_collection: ^3.0.0
# built_value: ^5.2.0
  built_value:
    path: ../built_value
  plugin: ^0.2.0
  quiver: '>=0.21.0 <0.29.0'

dev_dependencies:
  build_test: ^0.10.0
  test: any
