include: package:pedantic/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  enable-experiment:
    - macros

linter:
  rules:
    - cast_nullable_to_non_nullable
